[package]
name = "cypher"
description = "High-performance, cross-platform screen recording API for Rust."
version = "0.0.1"
edition = "2021"
rust-version = "1.56"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
repository = "https://github.com/clearlysid/cypher"
documentation = "https://docs.rs/cypher"
keywords = ["screen", "recording", "video", "audio", "ffmpeg"]
categories = []
build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"