[package]
name = "cypher"
description = "Modern, high-performance screen capture library for Rust. Cross-platform."
version = "0.0.2"
edition = "2021"
rust-version = "1.71"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
repository = "https://github.com/clearlysid/cypher"
documentation = "https://docs.rs/cypher"
keywords = ["screen", "recording", "video", "audio", "ffmpeg"]
categories = []

[dependencies]
cpal = "0.15.2"
hound = "3.5.1"
image = "0.24.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows-capture = "1.0.26"
windows = { version = "0.51", features = [
	"Win32_Foundation",
	"Win32_Graphics_Gdi",
] }

[target.'cfg(target_os = "macos")'.dependencies]
tao-core-video-sys = "0.2.0"
core-graphics = "0.23.1"
screencapturekit = { path = "screencapturekit-rs/screencapturekit" }
