[package]
name = "cypher"
description = "High-performance, cross-platform screen recording API for Rust."
version = "0.0.1"
edition = "2021"
rust-version = "1.56"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
repository = "https://github.com/clearlysid/cypher"
documentation = "https://docs.rs/cypher"
keywords = ["screen", "recording", "video", "audio", "ffmpeg"]
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[target."cfg(target_os = \"windows\")".dependencies.windows-sys]
version = "0.42.0"
features = [
  "Win32_Foundation",
]

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
objc = "0.2"