[package]
name = "cypher"
description = "High-performance, cross-platform screen recording API for Rust."
version = "0.0.1"
edition = "2021"
rust-version = "1.56"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
repository = "https://github.com/clearlysid/cypher"
documentation = "https://docs.rs/cypher"
keywords = ["screen", "recording", "video", "audio", "ffmpeg"]
categories = []
build = "build.rs"

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-bridge-build = "0.1"

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.48"
features = [
    "Graphics", "Graphics_Display", "Graphics_Capture", "Foundation"
]

[target.'cfg(target_os = "macos")'.dependencies]
swift-bridge = "0.1"
