[package]
name = "cypher"
description = "High-performance, cross-platform screen recording API for Rust."
version = "0.0.1"
edition = "2021"
rust-version = "1.56"
license = "MIT"
authors = ["Siddharth Jha"]
readme = "README.md"
repository = "https://github.com/clearlysid/cypher"
documentation = "https://docs.rs/cypher"
keywords = ["screen", "recording", "video", "audio", "ffmpeg"]
categories = []
build = "build.rs"

[dependencies]
image = "0.24.7"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.48"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[target.'cfg(target_os = "macos")'.dependencies]
tao-core-video-sys = "0.2.0"
screencapturekit = "0.1.0"
